export const Users = [
    {
      id:1,
      profilePicture: "person/barack-obama.jpg",
      username: "Barack Obama",
    },
    {
      id:2,
      profilePicture: "person/Boris-Johnson.jpg",
      username: "Boris Johnson",
    },
    {
      id:3,
      profilePicture: "person/justin.jpg",
      username: "Justin",
    },
    {
      id:4,
      profilePicture: "person/merkel.jpg",
      username: "Merkel",
    },
    {
      id:5,
      profilePicture: "person/putin1.png",
      username: "Putin",
    },
    {
      id:6,
      profilePicture: "person/trump.jpg",
      username: "Trump",
    },
    {
      id:7,
      profilePicture: "person/Xi.jpg",
      username: "Xi Jinping",
    },
    {
      id:8,
      profilePicture: "person/modi.jpg",
      username: "Narendra Modi",
    },
    {
      id:9,
      profilePicture: "person/kp.jpg",
      username: "KP Oli",
    },
    {
      id:10,
      profilePicture: "person/kim.jpg",
      username: "Kim Jong-un",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Love For All, Hatred For None.",
      photo: "post/firstpost.jpg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "post/jonathan-cooper.jpg",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "post/gianpaolo-antonucci.jpg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "post/julen-rey.jpg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "post/mikhail-volkov.jpg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "post/daniel-pelaez.jpg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "post/david-dm.jpg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "post/gianpaolo-antonucci2.jpg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the world by being yourself.",
      photo: "post/mike-cox.jpg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "post/marek-piwnicki.jpg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];